name: build-and-deploy
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Generate CNAME for custom domain
        run: |
          mkdir -p docs
          echo "blog.lsklab.com" > docs/CNAME

      - name: Generate articles
        run: npm run build:articles

      - name: Build SPA
        run: |
          rm -f docs/index.html
          rm -rf docs/assets
          npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add docs/
          git commit -m "chore: Update built files" || echo "No changes to commit"
          git push origin main

      # gh-pages ブランチを使わず /docs を直接公開する設定なので
      # 「Upload Pages artifact」は不要
